### PR TITLE
better Klayout package

### PR DESCRIPTION
**Pull request by joamatab**
- make a salt klayout package
- rename gdsfactory.types to gdsfactory.typings, as `gdsfactory.types` will be deprecated
- move tests to top of the repo, to keep klayout package small and fast to download

I also registered `gdsfactory/globalfoundries-pdk-libs-gf180mcu_fd_pr.git/branches/klayout/klayout` in klayout SALT package manager (location of the `grain.xml`)

image

image

TODO:

- [ ] fix run DRC macro @atorkmabrains 

https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/28#issuecomment-1431428925

### CODE REVIEW

**Comment by atorkmabrains** [comment]
Thanks @joamatab for sharing. we are going to remove DRC from here.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 We need to take a look at this

**Comment by atorkmabrains** [comment]
@joamatab, Based on @proppy suggestion in #28, we will remove gds factory implementation from here and keep your package.

**Comment by atorkmabrains** [comment]
@joamatab I'll close this PR.

**Comment by joamatab** [comment]
Sounds good, thank you Amro

**Comment by atorkmabrains** [comment]
Closed PR based on discussion.

**Pull request closed without merging**
